add Carol to external issue templates
department-of-veterans-affairs/vets-design-system-documentation pull request #1168
Opened 2022-08-30 14:34 UTC by k80bowman

Carol requested that she be added back as an assignee on the external issue templates. I also added the `dst-engineering` label to the component development issue template.

2022-08-31 19:44 UTC, andresriveratoro approved these changes

2022-08-31 19:57 UTC, bkjohnson requested changes

2022-08-31 19:57 UTC, bkjohnson commented on .github/ISSUE_TEMPLATE/2_documentation_request_form.yml
> +assignees: 'caw310'
I spoke with Carol and it seemed like this doesn't solve any problems.

2022-08-31 20:56 UTC, k80bowman commented on .github/ISSUE_TEMPLATE/2_documentation_request_form.yml
> +assignees: 'caw310'
Should I just close this PR?

2022-08-31 21:56 UTC, bkjohnson commented on .github/ISSUE_TEMPLATE/2_documentation_request_form.yml
> +assignees: 'caw310'
That's fine with me, but I'll remove the request in case you want to keep the `dst-engineering` label

2022-09-01 13:05 UTC, k80bowman commented on .github/ISSUE_TEMPLATE/2_documentation_request_form.yml
> +assignees: 'caw310'
I'll do that in a different PR.

2022-09-01 13:05 UTC, closed without merging