Update files.md
department-of-veterans-affairs/vets-design-system-documentation pull request #1279
Opened 2022-10-10 21:00 UTC by GnatalieH

Made some minor copy edits.

2022-10-11 18:55 UTC, humancompanion-usds commented on src/_patterns/ask-users-for/files.md
> -### Layout details
We should keep the headers as they are in the Pattern template.

2022-10-11 18:56 UTC, humancompanion-usds commented on src/_patterns/ask-users-for/files.md
> +## Live application examples
Please get screenshots of these and add them to examples rather than just the links here. Thanks.

2022-10-11 18:59 UTC, humancompanion-usds commented on src/_patterns/ask-users-for/files.md
> +
These really should get added by us or the content team to the Messages dictionary. There are already file upload related messages here: https://design.va.gov/content-style-guide/error-messages/feedback

2022-10-11 19:00 UTC, humancompanion-usds requested changes
Left comments inline on what to change. Once that's done you can push this out but then I'd like to get some feedback from Allison on whether this answers questions she'd expect designers to have.

2022-10-11 19:37 UTC, GnatalieH commented on src/_patterns/ask-users-for/files.md
> -* **Required documentation.** When a user must upload a file in order to provide required documentation.
Oh OK! I didn't know if this was old or not. Gotcha.

2022-10-11 19:38 UTC, GnatalieH commented on src/_patterns/ask-users-for/files.md
> +## Live application examples
Will do.

2022-10-11 19:38 UTC, GnatalieH commented on src/_patterns/ask-users-for/files.md
> -### Layout details
> Left comments inline on what to change. Once that's done you can push this out but then I'd like to get some feedback from Allison on whether this answers questions she'd expect designers to have.

Thanks! I'll address your comments and circle back with Allison.

2022-10-11 19:57 UTC, GnatalieH commented on src/_patterns/ask-users-for/files.md
> +## Live application examples
Can these go in an Examples section like we do with other patterns?

2022-10-12 14:37 UTC, humancompanion-usds commented on src/_patterns/ask-users-for/files.md
> +## Live application examples
Yes, add them to Examples.

2022-10-13 18:36 UTC, humancompanion-usds approved these changes

2022-10-14 17:40 UTC, humancompanion-usds commented
@GnatalieH - I feel like we got more feedback from Beth than this:
> The content preceding the File input component will vary depending on what file you are asking the user to upload. Work with a content specialist on how to ask for certain documents. 

However, it looks like that the content considerations are already captured in the File input component. Thus I would like there (and reuse the same formatting and text of the last bullet to reference the messages dictionary): https://design.va.gov/components/form/file-input#content-considerations

Otherwise this looks good to go!

2022-10-14 18:18 UTC, GnatalieH commented
> @GnatalieH - I feel like we got more feedback from Beth than this:
> 
> > The content preceding the File input component will vary depending on what file you are asking the user to upload. Work with a content specialist on how to ask for certain documents.
> 

This verbiage was partially left over from the current documentation. I modified some language to mention the File input component. Should I remove it? 

> However, it looks like that the content considerations are already captured in the File input component. Thus I would like there (and reuse the same formatting and text of the last bullet to reference the messages dictionary): https://design.va.gov/components/form/file-input#content-considerations
> 
> Otherwise this looks good to go!

OK I'm going to copy + paste the Content considerations from File input component to this pattern, retaining the formatting (unless it's possible to do an include using the deep link to [File input/Content considerations](https://design.va.gov/components/form/file-input#content-considerations)). Thanks!

2022-10-17 17:08 UTC, humancompanion-usds approved these changes

2022-10-17 17:24 UTC, merged