Update alert.md
department-of-veterans-affairs/vets-design-system-documentation pull request #1340
Opened 2022-11-14 21:56 UTC by GnatalieH

Began adding Placement guidance for Default and Background only alerts.

2022-11-16 21:52 UTC, humancompanion-usds requested changes
I'm not sure the examples relate to the changes we're making here to better define background-only Alerts. Also, let's try to minimize the example images to just showing what is relevant rather than the the entire page.

2022-11-16 22:19 UTC, GnatalieH commented on src/_components/alert.md
> +* Background color only alerts should be placed directly below the H1 and intro text when the alert applies to the entire page.
> What is the use case for background-only Alerts that apply to the entire page?

<img width="481" alt="image (19)" src="https://user-images.githubusercontent.com/88347129/202306684-4f3487ea-f04f-4af4-8ad1-cb86bd39a924.png">

2022-11-17 21:01 UTC, humancompanion-usds commented
### Background only placement and rules

* Appropriate when placed within a container such as a Card or other box.
* Errors related to a field or section are below the label, legend, or header.
* Info can appear between a section.
*

2022-12-01 21:19 UTC, GnatalieH commented
@humancompanion-usds I changed Previous to Back and am hoping for your review so we can merge this PR. Thanks!

2022-12-01 22:24 UTC, humancompanion-usds approved these changes

2022-12-01 22:35 UTC, merged