Update index.md
department-of-veterans-affairs/vets-design-system-documentation pull request #2523
Opened 2024-02-22 13:50 UTC by coforma-jamie

As part of OCTO's initiative to improve accessibility documentation across VA.gov, this page has been restructured to  a) give a more thorough explanation of our approach, b) provide resources to non-VA teams, who use the VADS as a North Star, and c) give VA teams a more comprehensive starting point.

We're also working on a more internal-facing page that will be posted to Platform. We'll link to it here once that's complete.

If you have any questions, please reach out to Martha Wilkes. :) Thank you!

2024-02-22 17:16 UTC, humancompanion-usds requested changes
Overall this is great and I'm happy to see it and merge it very soon. Just a few questions for you to think through. Thanks!

2024-02-22 17:16 UTC, humancompanion-usds commented on src/_about/accessibility/index.md
> +VA is here to serve Veterans of the United States military, and [approximately 40% have an identified disability](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/a
We've tried to stop deep linking into GitHub. Can we find the original statistic and cite that?

2024-02-22 17:16 UTC, humancompanion-usds commented on src/_about/accessibility/index.md
> +The VA Design System provides accessible components, the guidance to implement these components, and the tools to customize and extend the design system accessibly.
There should be some mention that we are built on the USWDS with a link to their Accessibility guidance: https://designsystem.digital.gov/documentation/accessibility/

2024-02-22 17:16 UTC, humancompanion-usds commented on src/_about/accessibility/index.md
> +- [Our plain language guidelines](https://design.va.gov/content-style-guide/plain-language/)
Could you separate this one out since it is not on the VA Platform site, but instead in the Design System? Thanks.

2024-02-22 17:16 UTC, humancompanion-usds commented on src/_about/accessibility/index.md
> +### Get accessibility guidance early from the CAIA team
I thought Martha wanted to pull this into the VA Platform site and not mention CAIA here and that this section was what touched off an effort to figure out what goes where. If this information is available on VA Platform, I'd be okay with removing this and just linking to there. If not, perhaps it should move there and be the first link in the Resources section? If it does stay, it should probably go above the Resources section as it is required for VFS teams.

2024-02-22 17:16 UTC, humancompanion-usds commented on src/_about/accessibility/index.md
> +As part of staging reviews, new components must also complete [advanced testing with an accessibility specialist](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-a
I agree that we want teams to do this testing "at a minimum" but we don't really indicate here what a maximum effort would look like. Perhaps adding a list of other devices they could or should test with would be useful which would follow the minimum list? Or is the Note sufficient?

2024-02-22 20:11 UTC, coforma-jamie commented on src/_about/accessibility/index.md
> +VA is here to serve Veterans of the United States military, and [approximately 40% have an identified disability](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/a
Sure! The stat comes from Statista, [Number of veterans in the United States in 2022, by service-connected disability status](https://www.statista.com/statistics/250316/us-veterans-by-disability-status/). If you combine all the rated Vets, and divide by the non-rated (or no-rating-reported) Vets, you get 39.5%.

How should we proceed - link to Statista directly?

2024-02-22 20:16 UTC, coforma-jamie commented on src/_about/accessibility/index.md
> +The VA Design System provides accessible components, the guidance to implement these components, and the tools to customize and extend the design system accessibly.
How about a paragraph after this:

The VA Design system was built on top of a fork of the U.S. Web Design System (USWDS), which prioritizes accessibility throughout. Learn more about [how USWDS practices accessibility](https://designsystem.digital.gov/documentation/accessibility/).

2024-02-22 20:18 UTC, coforma-jamie commented on src/_about/accessibility/index.md
> +- [Our plain language guidelines](https://design.va.gov/content-style-guide/plain-language/)
By "separate out," do you mean not include in the list? I'd love to keep it here if possible, since this is a list of VA resources for different disciplines, regardless of where the content "lives".

Also for context, we're close to adding a VFS-specific accessibility landing page on Platform. At that time, the plan is to remove this list and replace it with a reference to the new landing page.

2024-02-22 20:20 UTC, coforma-jamie commented on src/_about/accessibility/index.md
> +### Get accessibility guidance early from the CAIA team
The idea was to consider what audiences use the VADS, and I came up with two broad ones - VFS teams, and others who use this as a North Start but aren't a part of VA. Martha seemed fine to leave the reference here, as long as it was clear that it's for the VFS team audience, and not the global audience.

But I agree, putting it before the Resources makes a lot of sense! Is that something you do on your end, or can I do it from within this PR?

2024-02-22 20:22 UTC, coforma-jamie commented on src/_about/accessibility/index.md
> +As part of staging reviews, new components must also complete [advanced testing with an accessibility specialist](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-a
Checking with Martha, will tell you her answer :)

2024-02-22 21:15 UTC, humancompanion-usds commented on src/_about/accessibility/index.md
> +VA is here to serve Veterans of the United States military, and [approximately 40% have an identified disability](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/a
Yeah, seems reputable enough to me. Let's do that.

2024-02-22 21:17 UTC, humancompanion-usds commented on src/_about/accessibility/index.md
> +### Get accessibility guidance early from the CAIA team
You should be able to move it. Let me know if you have trouble.

2024-02-22 22:49 UTC, artsymartha68 commented on src/_about/accessibility/index.md
> +As part of staging reviews, new components must also complete [advanced testing with an accessibility specialist](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-a
Maximum. Wow. We've never had that luxury to even conceive of! I think I'd add
- TalkBack on an Android device (then the question comes which one from the millions available)
- NVDA with Chrome (we heard today from [the newest WebAIM survey](https://webaim.org/projects/screenreadersurvey10/) that NVDA is surpassing JAWS)

2024-02-26 22:30 UTC, humancompanion-usds approved these changes

2024-02-26 22:38 UTC, merged