Add missing icons and requesting new icons guidance
department-of-veterans-affairs/vets-design-system-documentation pull request #2789
Opened 2024-05-01 16:17 UTC by danbrady

2024-05-01 17:11 UTC, Andrew565 commented on src/_foundation/icons.html
> +    <strong>Check Existing Icons</strong>:</strong>
There's an extra </strong> closing tag here. Not hurting anything, just pointing it out.

2024-05-01 20:03 UTC, humancompanion-usds commented on src/_foundation/icons.html
> +    <strong>Explore Material Icons</strong>:
I'd want them to go to USWDS first and foremost, then to Material if they cannot find what they need. https://designsystem.digital.gov/components/icon/

2024-05-01 20:04 UTC, humancompanion-usds requested changes
Need to point them to USWDS first, then to Google. I would down play calling it Material. Folks outside of the Platform may get the notion that we are using Material, which we're really not.

2024-05-02 13:54 UTC, danbrady commented
Thanks, @humancompanion-usds. I updated the content to steer folks to USWDS before Material. Let me know if that makes more sense. Thanks!

2024-05-02 18:57 UTC, humancompanion-usds approved these changes

2024-05-02 19:00 UTC, merged