Experimental design content updates
department-of-veterans-affairs/vets-design-system-documentation pull request #3616
Opened 2024-12-13 22:02 UTC by briandeconinck

Content updates to [align content with the new experimental design flow in Mural](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96032).

2024-12-16 17:53 UTC, humancompanion-usds commented on src/_about/contributing/suggest-an-addition-or-update.html
> +      Note that even if the Design System Council approves your component or pattern before you conduct research, you must still validate your work with user research and present your findings to the
This is not my expectation. They can come back with their findings but they can also just attached them to the issue and ping the DST.

2024-12-16 17:54 UTC, humancompanion-usds commented on src/_about/contributing/suggest-an-addition-or-update.html
> +      When you are ready to present, post in the <a href="https://dsva.slack.com/archives/C01DBGX4P45">#platform-design-system</a> Slack channel and tag Carol Wong to alert the team that you have fil
Can we use site.slack_channel_link and {{ site.slack_channel_name }} like we did before?

2024-12-16 17:57 UTC, humancompanion-usds requested changes
Just left 2 comments.

2024-12-17 22:08 UTC, shiragoodman approved these changes

2024-12-18 21:13 UTC, briandeconinck commented on src/_about/contributing/suggest-an-addition-or-update.html
> +      When you are ready to present, post in the <a href="https://dsva.slack.com/archives/C01DBGX4P45">#platform-design-system</a> Slack channel and tag Carol Wong to alert the team that you have fil
Done.

2024-12-18 21:20 UTC, briandeconinck commented on src/_about/contributing/suggest-an-addition-or-update.html
> +      Note that even if the Design System Council approves your component or pattern before you conduct research, you must still validate your work with user research and present your findings to the
Rewrote to match these expectations.

2024-12-18 21:45 UTC, it-harrison approved these changes

2024-12-20 21:07 UTC, humancompanion-usds approved these changes

2024-12-20 21:08 UTC, merged