34126 Accordion Documentation Fix Storybook
department-of-veterans-affairs/vets-design-system-documentation pull request #613
Opened 2021-12-30 15:10 UTC by pdavies88

2021-12-30 16:00 UTC, andresriveratoro approved these changes

2022-01-03 14:19 UTC, k80bowman requested changes

2022-01-03 14:19 UTC, k80bowman commented on src/_components/accordions.md
> +## Only Open One
I'd like to call this "Single Select" instead of "Only Open One". Please also add a short description of the open-single prop and what it does.

2022-01-03 14:19 UTC, k80bowman commented on src/_components/accordions.md
> +{% include storybook-preview.html story="components-va-accordion--only-open-one" %}
Could we please rename this story "components-va-accordion--single-select"?

2022-01-04 12:03 UTC, pdavies88 commented on src/_components/accordions.md
> +## Only Open One
I have updated

2022-01-04 12:03 UTC, pdavies88 commented on src/_components/accordions.md
> +{% include storybook-preview.html story="components-va-accordion--only-open-one" %}
I have updated this PR and fixed the story in the component library pr to match

2022-01-04 13:46 UTC, k80bowman commented on src/_components/accordions.md
> +* Utilization of the `open-single` prop on the `va-accordion` component will change the accordion from multi-selectable to single-select
I'd like to change this description to make it a little more understandable. 
```suggestion
* Adding an `open-single` prop on the `va-accordion` component will allow the user to only open one accordion at a time.
```

2022-01-04 13:52 UTC, k80bowman approved these changes
Looks great, thank you!

2022-01-04 14:11 UTC, merged