CHORE: added new omb info page in docs
department-of-veterans-affairs/vets-design-system-documentation pull request #643
Opened 2022-02-09 15:50 UTC by mendacitees

![image](https://user-images.githubusercontent.com/5603893/153236087-22a4c501-c816-497f-87cb-0ddd8b52e1da.png)

New page omb-info.md file was added.  This file contains all that is needed for the Jekyll build process to generate the HTML page with the examples on it, as well as add the necessary items to the left hand navigation.  
Still working on the Accessibility section.  There is just placeholder text in that section currently.

2022-02-09 16:19 UTC, mendacitees commented
Question regarding Accessibility:  In reading through our own documentation, it is mentioned that items that link to a new page should be action links and not buttons.  In this case, it opens a modal.  Is that the way it should be?  I was looking for additional information on "Action Links" and discovered a missing page.  There are several links to:  https://design.va.gov/components/action-links which is currently generating a 403 error.

2022-02-11 15:33 UTC, k80bowman commented on src/_components/buttons.md
> +* Using buttons and links intentionally results in a more inclusive experience for assistive technology users. Make sure to read both button and [action link](https://design.va.gov/experimental-desig
thanks for fixing all of these!

2022-02-11 15:36 UTC, k80bowman requested changes
Looks great, just a couple of sections we can delete for now.

2022-02-11 15:36 UTC, k80bowman commented on src/_components/omb-info.md
> +
This can be deleted

2022-02-11 15:36 UTC, k80bowman commented on src/_components/omb-info.md
> +* Related Item 2
This can be deleted as well

2022-02-15 15:29 UTC, merged